//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalSemestre.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservacion
    {
        public int AD_Reservacion { get; set; }
        public System.DateTime FechaEntrada { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public int TotalaPagar { get; set; }
        public int CantidaddeDias { get; set; }
        public int EstadodePago { get; set; }
        public string Descripcion { get; set; }
        public string Rut_Cliente { get; set; }
        public int Numero { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual EstadoReservacion EstadoReservacion { get; set; }
        public virtual Habitacion Habitacion { get; set; }
    }
}
