//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalSemestre.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int idUsuario { get; set; }
        public string userNombre { get; set; }
        public string userClave { get; set; }
        public int idEstado { get; set; }
        public int idRol { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
